2025-02-16 20:27:51,500:DEBUG:certbot._internal.main:certbot version: 3.2.0
2025-02-16 20:27:51,500:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2025-02-16 20:27:51,500:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--email', 'sysadmin@ibc-victoria.com', '--agree-tos', '--no-eff-email', '--webroot-path=/var/lib/letsencrypt', '-d', 'ibc-victoria.ru']
2025-02-16 20:27:51,501:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-02-16 20:27:51,512:DEBUG:certbot._internal.log:Root logging level set at 30
2025-02-16 20:27:51,512:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2025-02-16 20:27:51,512:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A separate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7d8d77195580>
Prep: True
2025-02-16 20:27:51,513:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7d8d77195580> and installer None
2025-02-16 20:27:51,513:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2025-02-16 20:27:51,550:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2232619275', new_authzr_uri=None, terms_of_service=None), c6ff7ca1dac57f40dd0ec40a6ecce0c1, Meta(creation_dt=datetime.datetime(2025, 2, 16, 19, 25, 15, tzinfo=datetime.timezone.utc), creation_host='0b69fe2a988a', register_to_eff=None))>
2025-02-16 20:27:51,551:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-02-16 20:27:51,552:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-02-16 20:27:52,028:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 828
2025-02-16 20:27:52,029:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 16 Feb 2025 20:27:51 GMT
Content-Type: application/json
Content-Length: 828
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "The same profile you're accustomed to"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "oPdD7V5ys_g": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-02-16 20:27:52,031:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for ibc-victoria.ru
2025-02-16 20:27:52,033:DEBUG:acme.client:Requesting fresh nonce
2025-02-16 20:27:52,033:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-02-16 20:27:52,193:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-02-16 20:27:52,194:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 16 Feb 2025 20:27:52 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: KDHPPURR1pzqor4SQkogycsYvIjZt_zoEaJeaJ42STufDXHgJ-8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-02-16 20:27:52,194:DEBUG:acme.client:Storing nonce: KDHPPURR1pzqor4SQkogycsYvIjZt_zoEaJeaJ42STufDXHgJ-8
2025-02-16 20:27:52,195:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "ibc-victoria.ru"\n    }\n  ]\n}'
2025-02-16 20:27:52,201:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjIzMjYxOTI3NSIsICJub25jZSI6ICJLREhQUFVSUjFwenFvcjRTUWtvZ3ljc1l2SWpadF96b0VhSmVhSjQyU1R1ZkRYSGdKLTgiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "UKGnKfRzU4XcgEceprBDTW9_umgqs29xzE8D91bC6foJl8T-HB2H8_pXk-iWxZKJgJbIvgPHxjwydoakfXjJCrz7PeWoQ9bdrlz4PB9whP72ZbEyiy1IVXrjVRUfHXH-J3_xghVX5LFloB_-25C6PZo684l6_4-bmulhxeVs0diwlhnMP-XPn64p5B1EDyVZweTuYLnuzxwkCHKgvHpJoNzaufsk_M25OWMFNSybZohacgvT7n2p1c4_kwn59SySB-zHBjreycN44A8PKHnczkk6TgUrNMKRQYJAL_9P83sQFAZXivWmkzgUP8uXMDONSbLE16BUEG5-1G1mdFZDQA",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImliYy12aWN0b3JpYS5ydSIKICAgIH0KICBdCn0"
}
2025-02-16 20:27:52,386:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 296
2025-02-16 20:27:52,387:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Sun, 16 Feb 2025 20:27:52 GMT
Content-Type: application/problem+json
Content-Length: 296
Connection: keep-alive
Boulder-Requester: 2232619275
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/docs/rate-limits>;rel="help"
Replay-Nonce: KDHPPURRaKAG9C5N2lw7krdR0ijdh4A6uB5nAnJDSh5PbpoFscI
Retry-After: 62

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "too many failed authorizations (5) for \"ibc-victoria.ru\" in the last 1h0m0s, retry after 2025-02-16 20:28:53 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account",
  "status": 429
}
2025-02-16 20:27:52,388:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1871, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1577, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 519, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 429, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 480, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 143, in new_order
    response = self._post(self.directory['newOrder'], order)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 374, in _post
    return self.net.post(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 747, in post
    return self._post_once(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 760, in _post_once
    response = self._check_response(response, content_type=content_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 611, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: too many failed authorizations (5) for "ibc-victoria.ru" in the last 1h0m0s, retry after 2025-02-16 20:28:53 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
2025-02-16 20:27:52,398:ERROR:certbot._internal.log:An unexpected error occurred:
2025-02-16 20:27:52,399:ERROR:certbot._internal.log:too many failed authorizations (5) for "ibc-victoria.ru" in the last 1h0m0s, retry after 2025-02-16 20:28:53 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account
2025-02-16 20:27:52,400:DEBUG:certbot.util:Exception occurred releasing lock: LockFile(/var/lib/letsencrypt/.certbot.lock) <released>
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/util.py", line 241, in _release_locks
    dir_lock.release()
  File "/opt/certbot/src/certbot/certbot/_internal/lock.py", line 66, in release
    self._lock_mechanism.release()
  File "/opt/certbot/src/certbot/certbot/_internal/lock.py", line 172, in release
    os.remove(self._path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/letsencrypt/.certbot.lock'
